# Generated by Django 5.0.4 on 2025-11-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_title', models.CharField(blank=True, max_length=200, null=True)),
                ('achievement_description', models.TextField(blank=True, null=True)),
                ('achievement_icon', models.ImageField(blank=True, null=True, upload_to='achievements/')),
                ('achievement_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(blank=True, max_length=200, null=True)),
                ('partner_logo', models.ImageField(blank=True, null=True, upload_to='partners/')),
                ('partner_website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=200, null=True)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_link', models.URLField(blank=True, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=200, null=True)),
                ('service_description', models.TextField(blank=True, null=True)),
                ('service_icon', models.ImageField(blank=True, null=True, upload_to='services/')),
            ],
        ),
        migrations.CreateModel(
            name='team_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(blank=True, max_length=100, null=True)),
                ('member_role', models.CharField(blank=True, max_length=100, null=True)),
                ('member_photo', models.ImageField(blank=True, null=True, upload_to='team_members/')),
                ('member_bio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='first_name',
        ),
    ]
