# Generated by Django 5.0.4 on 2025-11-03 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_achievements_partners_projects_services_team_members_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievements',
            old_name='achievement_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='achievements',
            old_name='achievement_icon',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='achievements',
            old_name='achievement_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='achievements',
            old_name='achievement_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='partners',
            old_name='partner_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='partners',
            old_name='partner_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='partners',
            old_name='partner_website',
            new_name='website',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='product_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='product_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='product_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='service_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='service_icon',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='service_name',
            new_name='name',
        ),
    ]
