# Generated by Django 5.0.4 on 2025-11-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_achievement_description_achievements_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='ligne',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
