# Generated by Django 5.0.4 on 2025-11-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_partners_ligne'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='projects/covers/'),
        ),
    ]
